program: train.py
method: bayes
name: <PROJECT_NAME>
dataset_path: <DATASET_PATH>
project: <PROJECT_NAME>
entity: <user>
metric:
  name: f1
  goal: maximize
parameters:
  max_depth:
    min: 1
    max: 50
  min_split_loss:
    min: 0.0
    max: 10.0
  n_estimators:
    min: 5
    max: 250
  learning_rate:
    min: 0.05
    max: 0.4