name: led3_score
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6,<3.10
  - graphviz>=2.38,<3.0
  - rdkit=>2019.09.1
  - pytables>=3.7.0,<4.0.0
  - pip>=20.0 
  - poetry>=1.1.4,<2.0